version: '3.1'
services:
  mongo:
    image: mongo:5.0.22
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: msr
      MONGO_INITDB_ROOT_PASSWORD: fooBar
    ports:
      - 27017:27017

  uploader:
    depends_on:
      - mongo
    build:
      dockerfile: Dockerfile
      context: .
    container_name: uploader
    environment:
      - MONGO_IP=mongo
    stdin_open: true
    tty: true
    command:
      - bash
